name: Check for Code Clones (jscpd)

# Pull Requestが作成・更新された時に実行
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  find_code_clones:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウトします。
      # fetch-depth: 0 は全履歴を取得し、PRのベースブランチとの正確な比較に役立ちます。
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. jscpdアクションを実行します。
      - name: Run jscpd action
        uses: jscpd/jscpd-action@v3 # または最新のメジャーバージョンを指定
        with:
          # リポジトリのルートからスキャンを開始
          path: './'

          # チェック対象の言語・ファイルを指定
          pattern: '**/*.{js,py,html,css}'

          # --- ここが重要です ---
          # trueにすると、画像のようにPull Requestにコメントで結果を報告します。
          post-comment: 'true' # 文字列として'true'を指定するのがより確実です

          # 重複が見つかった場合にチェックを失敗させます (マージをブロックできます)
          fail-on-duplicate: 'true' # 文字列として'true'を指定するのがより確実です

          # スキャンから除外するディレクトリやファイルを指定します
          ignore: |
            **/node_modules/**
            **/dist/**
            **/build/**
